title: allowed
description: A tool that checks if Python code only uses a defined subset of the language.
show_downloads: false
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
